### PR TITLE
Minor fixes (proposal)

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Review by juanibiapina — APPROVED** [review]
Why not merge this?

**Comment by markstos** [comment]
@juanibiapina The project is not maintained anymore. Feel free to fork and release.

**Comment by qrush** [comment]
Starting to bring it back into shape :bowtie: - couldn't commit to this for, well, 9 years. Thanks for the fixes!

**Comment by markstos** [comment]
@qrush Glad to see some maintenance again. I'm still pretty happy with the tool-- Easy to get use, gets out the way, not much new to learn to use it.

Once set up, new commands can be written in Node.js, Fish or another language of your choice-- our use of it is not limited to bash scripting.

**Pull request merged**
